console.log('----ex04----');
var x = 0;
console.log("           x = ", x);
x += 10;
console.log("x += 10    x = ", x);
x -= 5;
console.log("x -= 5     x = ", x);
x *= 10;
console.log("x *= 10    x = ", x);
x /= 5;
console.log("x /= 5     x = ", x);
x %=3;
console.log("x %= 3     x = ", x);