console.log("-----ex06-----");
var a = 1;
var b = 3;
console.log("a : ", a);
console.log("b : ", b);
console.log("a == b     : ", a==b);
console.log("a == '1'   : ", a=='1');
console.log("a === '1'  : ", a==='1');
console.log("a != b     : ", a!=b);
console.log("a !== '1'  : ", a!=='1');
console.log("a > 1      : ", a > 1);
console.log("a >= 1     : ", a >= 1);
console.log("a < 1      : ", a < 1);
console.log("a <= 1     : ", a <= 1);